<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('products')->insert([
            [
                'title' => 'Sweet Peppers',
                'short_description' => 'Their high juice content enhances their firmness, crispness, and crunchiness. When grilled, red sweet peppers bring out their natural sweetness and flavour. These are firm, crispy, and crisp. The nutritious value and sugary flavour of yellow sweet peppers make them a healthy food choice.',
                'full_description' => '',
                'price' => 10.00,
                'quantity' => 50,
                'image_path' => '/images/products/',
                'image_name' => 'product1-1.jpg',
                'category' => 'vegetable',
                'classification' => 'default',
                'status' => 'active',
                'created_at' => Carbon::now(),
                'updated_at' => null,
            ],
            [
                'title' => 'Strawberries',
                'short_description' => 'A strawberry is both a low-growing, flowering plant and also the name of the fruit that it produces. Strawberries are soft, sweet, bright red berries. They\'re also delicious. Strawberries have tiny edible seeds that grow all over their surface.',
                'full_description' => '',
                'price' => 75.00,
                'quantity' => 50,
                'image_path' => '/images/products/',
                'image_name' => 'product1-2.jpg',
                'category' => 'fruit',
                'classification' => 'default',
                'status' => 'active',
                'created_at' => Carbon::now(),
                'updated_at' => null,
            ],
            [
                'title' => 'Snow Peas',
                'short_description' => 'Snow peas are almost completely flat with little bumps where the tiny peas are inside the pod. The entire pod is eaten (including the peas). The term mangetout—French for \'eat all\'— can be used to describe these and sugar snap peas. Their crunchy texture and mild flavour lend them to versatile use, both raw and cooked.',
                'full_description' => '',
                'price' => 15.00,
                'quantity' => 50,
                'image_path' => '/images/products/',
                'image_name' => 'product1-3.jpg',
                'category' => 'vegetable',
                'classification' => 'default',
                'status' => 'active',
                'created_at' => Carbon::now(),
                'updated_at' => null,
            ],
            [
                'title' => 'Red Cabbage',
                'short_description' => 'Red cabbage is a nutrient-rich, cruciferous or Brassica vegetable that\'s related to broccoli, cauliflower, and kale. It\'s sometimes called purple cabbage because its leaves are a dark purple-reddish color. Red cabbage is usually a little smaller and denser than green cabbage, and it has a more peppery taste.',
                'full_description' => '',
                'price' => 20.00,
                'quantity' => 50,
                'image_path' => '/images/products/',
                'image_name' => 'product1-4.jpg',
                'category' => 'vegetable',
                'classification' => 'default',
                'status' => 'active',
                'created_at' => Carbon::now(),
                'updated_at' => null,
            ],
            [
                'title' => 'Tomato',
                'short_description' => 'The tomato fruit is globular or ovoid. Botanically, the fruit exhibits all of the common characteristics of berries; a simple fleshy fruit that encloses its seed in the pulp. The outer skin is a thin and fleshy tissue that comprises the remainder of the fruit wall as well as the placenta.',
                'full_description' => '',
                'price' => 30.00,
                'quantity' => 50,
                'image_path' => '/images/products/',
                'image_name' => 'product1-5.jpg',
                'category' => 'vegetable',
                'classification' => 'default',
                'status' => 'active',
                'created_at' => Carbon::now(),
                'updated_at' => null,
            ],
            [
                'title' => 'Broccoli',
                'short_description' => 'Broccoli (Brassica oleracea var. italica) is an edible green plant in the cabbage family (family Brassicaceae, genus Brassica) whose large flowering head, stalk, and small associated leaves are eaten as a vegetable. Broccoli is classified in the Italica cultivar group of the species Brassica oleracea.',
                'full_description' => '',
                'price' => 40.00,
                'quantity' => 50,
                'image_path' => '/images/products/',
                'image_name' => 'product1-6.jpg',
                'category' => 'vegetable',
                'classification' => 'default',
                'status' => 'active',
                'created_at' => Carbon::now(),
                'updated_at' => null,
            ],
            [
                'title' => 'Carrots',
                'short_description' => 'Carrot is a biennial, belonging to the family Apiaceae, and is an important vegetable for its fleshy edible, colorful roots. It varies in colour from white, yellow, orange, light purple, deep red to deep violet.',
                'full_description' => '',
                'price' => 10.00,
                'quantity' => 50,
                'image_path' => '/images/products/',
                'image_name' => 'product1-7.jpg',
                'category' => 'vegetable',
                'classification' => 'default',
                'status' => 'active',
                'created_at' => Carbon::now(),
                'updated_at' => null,
            ],
            [
                'title' => 'Onion',
                'short_description' => 'Onion, Herbaceous biennial plant (Allium cepa) of the family Alliaceae, probably native to southwestern Asia but now grown worldwide, and its edible bulb. Among the hardiest and oldest garden vegetable plants, onions bear a cluster of small, greenish white flowers on one or more leafless stalks.',
                'full_description' => '',
                'price' => 2.00,
                'quantity' => 50,
                'image_path' => '/images/products/',
                'image_name' => 'product1-8.jpg',
                'category' => 'vegetable',
                'classification' => 'default',
                'status' => 'active',
                'created_at' => Carbon::now(),
                'updated_at' => null,
            ],
            [
                'title' => 'Apples',
                'short_description' => 'The apple is one of the pome (fleshy) fruits. Apples at harvest vary widely in size, shape, colour, and acidity, but most are fairly round and some shade of red or yellow. The thousands of varieties fall into three broad classes: cider, cooking, and dessert varieties.',
                'full_description' => '',
                'price' => 3.00,
                'quantity' => 50,
                'image_path' => '/images/products/',
                'image_name' => 'product1-9.jpg',
                'category' => 'fruit',
                'classification' => 'default',
                'status' => 'active',
                'created_at' => Carbon::now(),
                'updated_at' => null,
            ],
            [
                'title' => 'Garlic',
                'short_description' => 'A herb growing from a strongly aromatic, rounded bulb composed of around 10 to 20 cloves covered in a papery coat. The long, sword-shaped leaves are attached to an underground stem and the greenish-white or pinkish flowers grow in dense, spherical clusters atop a flower stalk.',
                'full_description' => '',
                'price' => 5.00,
                'quantity' => 50,
                'image_path' => '/images/products/',
                'image_name' => 'product1-10.jpg',
                'category' => 'vegetable',
                'classification' => 'default',
                'status' => 'active',
                'created_at' => Carbon::now(),
                'updated_at' => null,
            ],
            [
                'title' => 'Red Chilli Peppers',
                'short_description' => 'Red chillies are hollow, and the pith and seeds are the hottest part. Many red chillies are milder than green chillies, although there are hundreds of varieties. Chilli heat is related to capsaicin content and measured in Scoville units.',
                'full_description' => '',
                'price' => 7.00,
                'quantity' => 50,
                'image_path' => '/images/products/',
                'image_name' => 'product1-11.jpg',
                'category' => 'vegetable',
                'classification' => 'gold',
                'status' => 'active',
                'created_at' => '2024-05-21 06:40:42',
                'updated_at' => '2024-06-15 17:15:13',
            ],
            [
                'title' => 'Vegi Juice 10 oz',
                'short_description' => 'Discover the refreshing essence of 100% natural vegetable juice, crafted to perfection in a convenient 10 oz bottle. Packed with vitamins and nutrients, this juice is ideal for health-conscious individuals seeking a delicious and wholesome beverage option.',
                'full_description' => '',
                'price' => 14.00,
                'quantity' => 50,
                'image_path' => '/images/products/',
                'image_name' => 'product1-12.jpg',
                'category' => 'vegetable',
                'classification' => 'gold',
                'status' => 'active',
                'created_at' => '2024-05-21 06:40:42',
                'updated_at' => '2024-06-15 17:15:13',
            ],
            [
                'title' => 'Chicken Breast 10 oz',
                'short_description' => 'Our Premium Chicken Breast is a high-quality, 10-ounce cut of boneless, skinless poultry known for its lean, tender meat and mild flavour. This versatile cut is ideal for a wide range of cooking methods, including grilling, baking, sautéing, or poaching, and is perfect for healthy meals and delicious recipes.',
                'full_description' => '',
                'price' => 60.00,
                'quantity' => 50,
                'image_path' => '/images/products/',
                'image_name' => 'product1-13.jpg',
                'category' => 'meat',
                'classification' => 'gold',
                'status' => 'active',
                'created_at' => '2024-05-21 06:40:42',
                'updated_at' => '2024-06-15 17:15:13',
            ],
            [
                'title' => 'Beef Steak 10 oz',
                'short_description' => 'Our Premium Beef Steak is a 10-ounce cut of high-quality beef known for its rich flavour and tender texture. Sourced from well-marbled cuts, this steak offers a juicy and satisfying eating experience that’s perfect for grilling, pan-searing, or broiling.',
                'full_description' => '',
                'price' => 75.00,
                'quantity' => 50,
                'image_path' => '/images/products/',
                'image_name' => 'product1-14.jpg',
                'category' => 'meat',
                'classification' => 'gold',
                'status' => 'active',
                'created_at' => '2024-05-21 06:40:42',
                'updated_at' => '2024-06-15 17:15:13',
            ],
            [
                'title' => 'Pork Chop 10 oz',
                'short_description' => 'Our Premium Pork Chops offer a delicious and versatile cut of pork, ideal for a variety of culinary creations. Each 10-ounce chop is expertly trimmed and delivers a perfect balance of tender meat and flavourful juiciness, making it an excellent choice for grilling, pan-frying, or baking.',
                'full_description' => '',
                'price' => 50.00,
                'quantity' => 50,
                'image_path' => '/images/products/',
                'image_name' => 'product1-15.jpg',
                'category' => 'meat',
                'classification' => 'gold',
                'status' => 'active',
                'created_at' => '2024-05-21 06:40:42',
                'updated_at' => '2024-06-15 17:15:13',
            ],
        ]);
    }
}
